version: '3.1'

services:
  db:
   image: mongo:latest
   restart: always
   container_name: trendigo-local-db
   ports:
    - '27017:27017'
   volumes:
    - mongodata:/data/db

  redis:
   image: redis
   container_name: trendigo-local-redis
   ports:
    - "6379:6379"
   volumes:
    - redisdata:/var/lib/redis

volumes:
  mongodata:
  redisdata:
